version: "3.7"

services:
    redis:
        image: redis:latest

    mongodb:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodbdata:/data/db

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb

    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: root

    elasticsearch:
        image: elasticsearch:7.3.1
        environment:
            - discovery.type=single-node

    kibana:
        image: kibana:7.3.1
        ports:
            - 5601:5601
    
    apmserver:
        image: docker.elastic.co/apm/apm-server:7.3.1

    instrumentality:
        build: .
        ports:
            - 80:80
        environment:
            - ELASTIC_APM_SERVER_URL=http://apmserver:8200
            - ELASTIC_APM_SERVICE_NAME=app
            - ELASTIC_APM_ENVIRONMENT=docker

volumes:
    mongodbdata:
